version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    depends_on:
      - mongo-seed

  mongo-seed:
    image: mongo:latest
    volumes:
      - ./dataset_clean.json:/datasets/dataset.json
    command: >
      mongoimport
        --host mongodb
        -d eurovisao
        -c edicoes
        --type json
        --file /datasets/dataset.json
        --jsonArray
